receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otelcol-metrics
          scrape_interval: 60s
          static_configs:
            - targets: [ "otel-collector:8888" ]

exporters:
  debug:
    verbosity: basic
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus/spanmetrics:
    endpoint: 0.0.0.0:9999
    metric_expiration: 75s
  opensearch:
    logs_index: otel-logs
    logs_index_time_format: "yyyy-MM-dd"
    http:
      endpoint: "http://opensearch:9200"
      tls:
        insecure: true

processors:
  batch:
  tail_sampling:
    decision_wait: 45s
    num_traces: 50000
    policies:
      - name: filter-and-sample
        type: and
        and:
          and_sub_policy:
            - name: not-healthcheck-http-user-agent
              type: string_attribute
              string_attribute: { key: http.user_agent, values: [ "kube-probe/.*", "Prometheus/.*", "Gravitee.io/.*", "ELB-HealthChecker/.*" ], enabled_regex_matching: true, invert_match: true }
            - name: not-healthcheck-request-header-user-agent
              type: string_attribute
              string_attribute: { key: request.header.user-agent, values: [ "kube-probe/.*", "Prometheus/.*", "Gravitee.io/.*", "ELB-HealthChecker/.*" ], enabled_regex_matching: true, invert_match: true }
            - name: not-healthcheck-http-request-header-user-agent
              type: string_attribute
              string_attribute: { key: http.request.header.user-agent, values: [ "kube-probe/.*", "Prometheus/.*", "Gravitee.io/.*", "ELB-HealthChecker/.*" ], enabled_regex_matching: true, invert_match: true }
            - name: probabilistic-50-percent
              type: probabilistic
              probabilistic: { sampling_percentage: 50 }

connectors:
  spanmetrics:
    dimensions:
      - name: http.method
      - name: http.request.method
      - name: http.status_code
      - name: http.response.status_code
      - name: http.user_agent
      - name: request.header.user-agent
      - name: http.request.header.user-agent
    histogram:
      explicit:
        buckets: [ 2ms, 10ms, 100ms, 1s, 10s ]

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ tail_sampling, batch ]
      exporters: [ otlp/jaeger, spanmetrics ]
    metrics:
      receivers: [ otlp, prometheus, spanmetrics ]
      processors: [ batch ]
      exporters: [ prometheusremotewrite, prometheus/spanmetrics ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, opensearch ]
