version: "3.8"

services:
  bets:
    build:
      dockerfile: Dockerfile
      context: ./bets
    environment:
      - OTEL_SERVICE_NAME=bets
      - MATCHES_URL=http://matches:8083
      - TEAMS_URL=http://teams:8084
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - LOGGING_PATTERN_LEVEL=trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p
      - JAVA_TOOL_OPTIONS=-javaagent:opentelemetry-javaagent.jar
    ports:
      - "8081:8081"
    restart: unless-stopped
  championships:
    build:
      dockerfile: Dockerfile
      context: ./championships
    environment:
      - OTEL_SERVICE_NAME=championships
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - LOGGING_PATTERN_LEVEL=trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p
      - JAVA_TOOL_OPTIONS=-javaagent:opentelemetry-javaagent.jar
    ports:
      - "8082:8082"
    restart: unless-stopped
  matches:
    build:
      dockerfile: Dockerfile
      context: ./matches
    environment:
      - OTEL_SERVICE_NAME=matches
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - CHAMPIONSHIPS_URL=http://championships:8082
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - LOGGING_PATTERN_LEVEL=trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p
      - JAVA_TOOL_OPTIONS=-javaagent:opentelemetry-javaagent.jar
    ports:
      - "8083:8083"
    restart: unless-stopped
  teams:
    build:
      dockerfile: Dockerfile
      context: ./teams
    environment:
      - OTEL_SERVICE_NAME=teams
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - LOGGING_PATTERN_LEVEL=trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p
      - JAVA_TOOL_OPTIONS=-javaagent:opentelemetry-javaagent.jar
    ports:
      - "8084:8084"
    restart: unless-stopped
